version: "3.9"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL_CONTAINER}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app_network

volumes:
  pgdata:
    driver: local

networks:
    app_network:
      name: app_network
